### PR TITLE
Fix for #4 : swap git for https protocol in submodules initialisation

### PR DESCRIPTION
**Pull request by kyzh**
Change git to https protocol, so people that can only access "the web" can clone it.

### CODE REVIEW

**Comment by Finkregh** [comment]
:-1: see my comment in #4

**Comment by ghost** [comment]
You can try this too: git config --global url."https://".insteadOf git:// (same comment in #4)

**Comment by kyzh** [comment]
Thanks, this is a perfect workaround provided in #4

**Comment by Dieterbe** [comment]
that workaround doesn't seem very healthy. it probably overrides push urls too?
i looked into all options again, and "found `git://` is the default so it should be used" not a very good argument.  "https://" seems best for fetch/clone urls, so i just pushed a commit to fix this

**Comment by kyzh** [comment]
:sparkling_heart:

**Pull request closed without merging**
